# .eslintrc.yaml
---
  extends: airbnb-base
  env:
    node: true
    mocha: true
    es6: true
  parser: typescript-eslint-parser
  parserOptions:
    sourceType: module
    ecmaFeatures:
      modules: true
  rules:
    "no-console": off
    "import/no-unresolved": off
    camelcase: off
    "import/prefer-default-export": off
    "prefer-destructuring": off
